### ISSUE TITLE
RSS/Atom feed to subscribe to blog

### ISSUE THREAD

**Issue by sangeet259** [kshitij10496/kshitij10496.github.io#1]
Hey @kshitij10496 , can you make your blog subscribable via RSS/Atom?

I would love to be notified of the things you write, what I have to do right now is periodically check your blog. It would be nice to have a subscription to it.

**Comment by kshitij10496** [comment]
An RSS feed is already being generated here: [RSS Feed](https://kshitij10496.github.io/index.xml)
This should be good for adding the blog to feed aggregators, such as Feedly.
Let me know if this works for you! 😄 

Glad to know that my blog has a couple of readers. 🎉

**Comment by sangeet259** [comment]
Hey Thanks, I forgot to close this one.
